### ISSUE TITLE
初始化不鲁棒

### ISSUE THREAD

**Issue by Sunnystaste** [hku-mars/VoxelMap#10]
VoxelMap总体性能很好，但是UAV在初始化时如果飞机一直在运动则并不鲁棒非常容易发散，请问这是为什么呢？演示视频中UAV也是从中途平飞静止时启动的算法，请问有没有什么好的解决方法呢？
![image](https://user-images.githubusercontent.com/37181135/183584162-b2777ccb-fc6b-42cd-b9fd-b670d1240c81.png)

**Comment by Sunnystaste** [comment]
演示视频可以很明显看出初始化时，飞机在高空静止，累积了足够数据生成平面后再开始运动。
但是实际情况下飞机会一直运动，没法控制初始化的实践，测试了一些数据发现算法在运动场景下的初始化确实不太鲁棒=-=

**Comment by Gatsby23** [comment]
> 演示视频可以很明显看出初始化时，飞机在高空静止，累积了足够数据生成平面后再开始运动。 但是实际情况下飞机会一直运动，没法控制初始化的实践，测试了一些数据发现算法在运动场景下的初始化确实不太鲁棒=-=

应该是动态初始化估计重力方向和IMU部分内参，你可以把程序当中这部分写死来看看效果
