### ISSUE TITLE
请问是否方便公开Unstructured Environment Test的数据集呢？

### ISSUE THREAD

**Issue by Sunnystaste** [hku-mars/VoxelMap#12]
非常感谢作者的作品，有效的平面评估使得我们的研究思路受益匪浅，尤其在解决退化场景时，有很好的效果。
请问您在论文中关于Mountain, Park的 Avia数据集方便公开么？这种高空单向的山地飞行数据很珍贵，也很难找到类似这么好的数据了=-=
![image](https://user-images.githubusercontent.com/37181135/188784635-0c217919-7225-42d7-8f8c-63782df97c37.png)

**Comment by ChongjianYUAN** [comment]
> 非常感谢作者的作品，有效的平面评估使得我们的研究思路受益匪浅，尤其在解决退化场景时，有很好的效果。 请问您在论文中关于Mountain, Park的 Avia数据集方便公开么？这种高空单向的山地飞行数据很珍贵，也很难找到类似这么好的数据了=-= ![image](https://user-images.githubusercontent.com/37181135/188784635-0c217919-7225-42d7-8f8c-63782df97c37.png)

您好，感谢您的关注，mars lab正在采集、整合高空数据集，这个数据会后续一起随文章公开，目前暂时无法单独开源该数据，您可以继续关注我们的后续工作，谢谢理解

**Comment by Sunnystaste** [comment]
好的，后续我会继续follow你们的研究的，加油。
