### ISSUE TITLE
计算世界系点云协方差的时候貌似存在bug

### ISSUE THREAD

**Issue by Sunnystaste** [hku-mars/VoxelMap#15]
袁博，抱歉请教几个问题！
1：在创建地图，更新地图，点云匹配时都会计算世界系下的协方差，代码中的多项式的第二项貌似少了旋转，请问这是一个bug么？
2：此处的point_crossmat是body系下的点，而非lidar系下的点。与论文不太相符，请问这是为什么呢？
![image](https://user-images.githubusercontent.com/37181135/198965911-b38bc2f3-5725-477a-bf2d-cd79755f1429.png)
![image](https://user-images.githubusercontent.com/37181135/198966472-f6b44715-beaf-47e0-8a36-fe922e3e78cc.png)
是否如下代码表示才是更符合论文原理的实现呢？
![image](https://user-images.githubusercontent.com/37181135/198967252-16c0ea55-4256-42be-9234-f4dac3a32632.png)

**Comment by Sunnystaste** [comment]
但做完修改后，性能的劣化比较严重，不知道袁博是什么看法

**Comment by HerB1998** [comment]
我也有同样的困惑，希望能得到解答

**Comment by Sunnystaste** [comment]
> 
袁博的邮件回复很好的解决了这个问题。
修改协方差表达式后，我按照avia官方的指标修改参数，之后数据也不发散了。
![image](https://user-images.githubusercontent.com/37181135/199867219-7123b22d-6e53-4f3d-bdbd-34fbf8302d15.png)

**Comment by fanhuigui** [comment]
> > 
> 
> 袁博的邮件回复很好的解决了这个问题。 修改协方差表达式后，我按照avia官方的指标修改参数，之后数据也不发散了。 ![image](https://user-images.githubusercontent.com/37181135/199867219-7123b22d-6e53-4f3d-bdbd-34fbf8302d15.png)

你好，我想问以下您有没有带 time 和 ring的bag包，集成了imu数据和点云数据的，我下载的序列6和7的bag包好像没有time和ring或者avia的，带真值轨迹的，一直卡在这里了

**Comment by fanhuigui** [comment]
> > 
> 
> 袁博的邮件回复很好的解决了这个问题。 修改协方差表达式后，我按照avia官方的指标修改参数，之后数据也不发散了。 ![image](https://user-images.githubusercontent.com/37181135/199867219-7123b22d-6e53-4f3d-bdbd-34fbf8302d15.png)

你好，我想问以下您有没有带 time 和 ring的bag包，集成了imu数据和点云数据的，我下载的序列6和7的bag包好像没有time和ring或者avia的，带真值轨迹的，一直卡在这里了

**Comment by fanhuigui** [comment]
> > 
> 
> 袁博的邮件回复很好的解决了这个问题。 修改协方差表达式后，我按照avia官方的指标修改参数，之后数据也不发散了。 ![image](https://user-images.githubusercontent.com/37181135/199867219-7123b22d-6e53-4f3d-bdbd-34fbf8302d15.png)

您好，我发现代码里面有一些问题，然后修改了以后，无法运行，一直出错，我觉得理论上我修改的没问题，然后卡在这几个星期了，[voxel_mapping_odom-2] process has died [pid 71230, exit code -11, cmd /home/fanhuigui/ws_livox/devel/lib/voxel_map/voxel_mapping_odom __name:=voxel_mapping_odom __log:=/home/fanhuigui/.ros/log/b745554a-df76-11ed-ae4a-25406821df27/voxel_mapping_odom-2.log].
log file: /home/fanhuigui/.ros/log/b745554a-df76-11ed-ae4a-25406821df27/voxel_mapping_odom-2*.log

**Comment by fanhuigui** [comment]
> > > 
> > 
> > 
> > 袁博的邮件回复很好的解决了这个问题。 修改协方差表达式后，我按照avia官方的指标修改参数，之后数据也不发散了。 ![image](https://user-images.githubusercontent.com/37181135/199867219-7123b22d-6e53-4f3d-bdbd-34fbf8302d15.png)
> 
> 您好，我发现代码里面有一些问题，然后修改了以后，无法运行，一直出错，我觉得理论上我修改的没问题，然后卡在这几个星期了，[voxel_mapping_odom-2] process has died [pid 71230, exit code -11, cmd /home/fanhuigui/ws_livox/devel/lib/voxel_map/voxel_mapping_odom __name:=voxel_mapping_odom __log:=/home/fanhuigui/.ros/log/b745554a-df76-11ed-ae4a-25406821df27/voxel_mapping_odom-2.log]. log file: /home/fanhuigui/.ros/log/b745554a-df76-11ed-ae4a-25406821df27/voxel_mapping_odom-2*.log

然后我发现代码有imu这个模块，就调用了这个模块

**Comment by fanhuigui** [comment]
> 我也有同样的困惑，希望能得到解您好，请问是不是这个buildvoxelmap这个函数有问题，我调试了好几周，发现这一块好像有问题

**Comment by fanhuigui** [comment]
> 我也有同样的困惑，希望能得到解答

您好，请问是不是这个buildvoxelmap这个函数有问题，我调试了好几周，发现这一块好像有问题

**Comment by Sunnystaste** [comment]
> > 我也有同样的困惑，希望能得到解答
> 
> 您好，请问是不是这个buildvoxelmap这个函数有问题，我调试了好几周，发现这一块好像有问题
emm你可以单步调试/cout输出日志，尝试debug试试看，函数本身不存在问题

**Comment by fanhuigui** [comment]
> > > 我也有同样的困惑，希望能得到解答
> > 
> > 
> > 您好，请问是不是这个buildvoxelmap这个函数有问题，我调试了好几周，发现这一块好像有问题
> > emm你可以单步调试/cout输出日志，尝试debug试试看，函数本身不存在问题
我调用了imu模块，因为我看代码里有这个函数模块，去畸变，然后我cout 发现到了buildvoxelmap这里就无法输出了，然后一直在前面初始化循环，scanindex一直为0，处理前能够正常输出点云个数，调用process处理后，无法打印点云个数，调试了三个星期，人都快崩溃了，唉，请问您用的是去畸变的点云吗

**Comment by HViktorTsoi** [comment]
> 袁博，抱歉请教几个问题！ 1：在创建地图，更新地图，点云匹配时都会计算世界系下的协方差，代码中的多项式的第二项貌似少了旋转，请问这是一个bug么？ 2：此处的point_crossmat是body系下的点，而非lidar系下的点。与论文不太相符，请问这是为什么呢？ ![image](https://user-images.githubusercontent.com/37181135/198965911-b38bc2f3-5725-477a-bf2d-cd79755f1429.png) ![image](https://user-images.githubusercontent.com/37181135/198966472-f6b44715-beaf-47e0-8a36-fe922e3e78cc.png) 是否如下代码表示才是更符合论文原理的实现呢？ ![image](https://user-images.githubusercontent.com/37181135/198967252-16c0ea55-4256-42be-9234-f4dac3a32632.png)

严格按照论文的Eq(3)实现，给point_crossmat那一项左右乘R之后（即第二个图的实现方式），在hilti某些序列上表现确实更好一些
