### ISSUE TITLE
只运行几帧就报错了

### ISSUE THREAD

**Issue by qpc001** [hku-mars/VoxelMap#17]
[ERROR] [1675417375.513728154]: Ignoring transform for child_frame_id "aft_mapped" from authority "unknown_publisher" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)

**Comment by jiejie567** [comment]
Hi?请教下你是怎么解决的？我也遇到了、

**Comment by qpc001** [comment]
> Hi?请教下你是怎么解决的？我也遇到了、

用的是速腾的雷达吗?

**Comment by Liming-Cheng** [comment]
hi @qpc001 @jiejie567 @XW-HKU , 请问这个问题最后解决了吗？我遇到的现象是有的雷达可以跑，有的不行。

**Comment by barbolar** [comment]
我也想知道怎么解决，我跑M2DGR数据集报这个错误了，用其他数据集没有出现这个错误

**Comment by LarryDong** [comment]
我看了下，我这边的报错原因就是里程计跟丢了。修改yaml配置文件的参数，修改的合适可以运行。

**Comment by KuMing1** [comment]
@LarryDong 请问你是怎么修改的？我也遇到了这个问题,yaml文件里面动哪里可以解决这块问题？

**Comment by LarryDong** [comment]
> [@LarryDong](https://github.com/LarryDong) 请问你是怎么修改的？我也遇到了这个问题,yaml文件里面动哪里可以解决这块问题？

主要是`voxel_size`，`plannar_threshold`，其次是mapping中的其他参数需要调整。其他的参数基本上是确定的。你搞清楚出原理，就知道哪些影响了。
