### ISSUE TITLE
哈希索引的代码问题

### ISSUE THREAD

**Issue by hr2894235132** [hku-mars/VoxelMap#19]
袁博您好，抱歉请教个问题：
```
for (int j = 0; j < 3; ++j) {
            loc_xyz[j] = p_v.point[j] / voxel_size;
            if (loc_xyz[j] < 0) loc_xyz[j] -= 1.0; // todo: ???
}
```
在计算哈希索引的时候，为什么为负的值都要减1操作呢？可能是我太菜了，但是我真的没有想明白，希望您能在百忙中帮我解答一下，万分感谢！

**Comment by Yeah2333** [comment]
你看这个图就明白了。
![7051676048277_](https://user-images.githubusercontent.com/22851247/218151280-9fd29a6d-d80f-4f50-b510-67531b8125d4.jpg)
如果不-1，取整后-0.1会和0.1在一个voxel内。这是错误的。

**Comment by hr2894235132** [comment]
非常感谢！！！恍然大悟
