### ISSUE TITLE
有关pcl::PointXYZINormal点云intensity，normal_x(y,z)，以及曲率更新的问题

### ISSUE THREAD

**Issue by hr2894235132** [hku-mars/VoxelMap#20]
袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
```
laserCloudOri->points[i].intensity = sqrt(R_inv(i));
laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
laserCloudOri->points[i].normal_y = sqrt(sigma_l);
laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
```

**Comment by ChongjianYUAN** [comment]
> 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> 
> ```
> laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> ```

不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分

**Comment by hr2894235132** [comment]
> > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > ```
> > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > ```
> 
> 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分

非常感谢袁博的回复！
这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？
![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)

**Comment by ChongjianYUAN** [comment]
> > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > ```
> > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > ```
> > 
> > 
> > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> 
> 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)

需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源

**Comment by hr2894235132** [comment]
> > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > ```
> > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > ```
> > > 
> > > 
> > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > 
> > 
> > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> 
> 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源

好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！

**Comment by hr2894235132** [comment]
> > > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > > ```
> > > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > > ```
> > > > 
> > > > 
> > > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > > 
> > > 
> > > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> > 
> > 
> > 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源
> 
> 好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！

袁博您好，已经成功用mid-70 + realsenseD455测试成功了，想问一下，可以同时发布三层的平面特征图吗？观察到现在只能每次在配置文件中选择去订阅单独一层。

**Comment by ChongjianYUAN** [comment]
> > > > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > > > ```
> > > > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > > > 
> > > > 
> > > > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> > > 
> > > 
> > > 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源
> > 
> > 
> > 好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！
> 
> 袁博您好，已经成功用mid-70 + realsenseD455测试成功了，想问一下，可以同时发布三层的平面特征图吗？观察到现在只能每次在配置文件中选择去订阅单独一层。

目前可以发布多层的平面特征图，配置文件中是设置发布至最深层数的平面，比如设置publish_max_voxel_layer为2，则发布0,1,2层的平面特征图

**Comment by hr2894235132** [comment]
> > > > > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > > > > ```
> > > > > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > > > > 
> > > > > 
> > > > > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> > > > 
> > > > 
> > > > 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源
> > > 
> > > 
> > > 好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！
> > 
> > 
> > 袁博您好，已经成功用mid-70 + realsenseD455测试成功了，想问一下，可以同时发布三层的平面特征图吗？观察到现在只能每次在配置文件中选择去订阅单独一层。
> 
> 目前可以发布多层的平面特征图，配置文件中是设置发布至最深层数的平面，比如设置publish_max_voxel_layer为2，则发布0,1,2层的平面特征图

嗷嗷，明白了。感谢袁博耐心回复！
那如果我想观察单独某一层的平面，可以实现吗？

**Comment by ChongjianYUAN** [comment]
> > > > > > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > > > > > ```
> > > > > > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > > > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > > > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > > > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > > > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > > > > > 
> > > > > > 
> > > > > > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> > > > > 
> > > > > 
> > > > > 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源
> > > > 
> > > > 
> > > > 好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！
> > > 
> > > 
> > > 袁博您好，已经成功用mid-70 + realsenseD455测试成功了，想问一下，可以同时发布三层的平面特征图吗？观察到现在只能每次在配置文件中选择去订阅单独一层。
> > 
> > 
> > 目前可以发布多层的平面特征图，配置文件中是设置发布至最深层数的平面，比如设置publish_max_voxel_layer为2，则发布0,1,2层的平面特征图
> 
> 嗷嗷，明白了。感谢袁博耐心回复！ 那如果我想观察单独某一层的平面，可以实现吗？

需要简单修改代码实现，具体步骤：修改下Plane结构以及pubVoxelMap函数，在Plane结构里增加一个成员变量layer用来记录plane所处的层数，然后在pubVoxelMap函数里给指定层数的平面赋值alpha，其余层数alpha赋值0

**Comment by hr2894235132** [comment]
> > > > > > > > > 袁博您好，抱歉打扰，想请教一下在计算测量的雅可比矩阵H的过程中，计算完点的协方差之后，代码中做了一步更新laserCloudOri中点的一些属性值（intensity，normal_x， normal_y， normal_z， curvature），更新的具体公式我不是很明白，在论文中也没有找到对应的部分，可以麻烦您在百忙中抽空给我解答一下吗？非常感谢。具体代码部分如下：
> > > > > > > > > ```
> > > > > > > > > laserCloudOri->points[i].intensity = sqrt(R_inv(i));
> > > > > > > > > laserCloudOri->points[i].normal_x = corr_normvect->points[i].intensity; // point-to-plane dist
> > > > > > > > > laserCloudOri->points[i].normal_y = sqrt(sigma_l);
> > > > > > > > > laserCloudOri->points[i].normal_z = sqrt(norm_vec.transpose() * cov * norm_vec);
> > > > > > > > > laserCloudOri->points[i].curvature = sqrt(sigma_l + norm_vec.transpose() * cov * norm_vec);
> > > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不好意思，这部分是以前开发过程中debug调试用的代码，对于程序运行是没有影响的，可以忽略此部分
> > > > > > > 
> > > > > > > 
> > > > > > > 非常感谢袁博的回复！ 这里还有个小问题，在计算雅可比矩阵过程中，不需要先把point_this（雷达坐标系）转换到IMU坐标系，再利用下面的公式转换到世界坐标系下吗？ ![image](https://user-images.githubusercontent.com/86639226/220501119-20e6c3a8-d505-444f-be60-d42466245054.png)
> > > > > > 
> > > > > > 
> > > > > > 需要的，加入IMU后，还需要考虑雷达body系的协方差的转换，这部分会在IMmesh开源时一并开源
> > > > > 
> > > > > 
> > > > > 好的，感谢袁博的回复！期待后续工作的开源，祝袁博工作顺利，身体健康，万事顺利！
> > > > 
> > > > 
> > > > 袁博您好，已经成功用mid-70 + realsenseD455测试成功了，想问一下，可以同时发布三层的平面特征图吗？观察到现在只能每次在配置文件中选择去订阅单独一层。
> > > 
> > > 
> > > 目前可以发布多层的平面特征图，配置文件中是设置发布至最深层数的平面，比如设置publish_max_voxel_layer为2，则发布0,1,2层的平面特征图
> > 
> > 
> > 嗷嗷，明白了。感谢袁博耐心回复！ 那如果我想观察单独某一层的平面，可以实现吗？
> 
> 需要简单修改代码实现，具体步骤：修改下Plane结构以及pubVoxelMap函数，在Plane结构里增加一个成员变量layer用来记录plane所处的层数，然后在pubVoxelMap函数里给指定层数的平面赋值alpha，其余层数alpha赋值0

好嘞，感谢袁博！
