### ISSUE TITLE
roslaunch failed

### ISSUE THREAD

**Issue by NEU-LC** [hku-mars/VoxelMap#4]
Thanks for your contribution!

I think there is a bug in the roslaunch file that prevents the code from working properly.

`<node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz" args="-d $(find voxel_mapping)/rviz_cfg/voxel_mapping.rviz" />`

should be:
`<node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz" args="-d $(find voxel_map)/rviz_cfg/voxel_mapping.rviz" />`

Otherwise，there will be a error when running the launch file as follows:

Resource not found: voxel_mapping
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/xxx/voxel_map_ws/src
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file

**Comment by ChongjianYUAN** [comment]
> Thanks for your contribution!
> 
> I think there is a bug in the roslaunch file that prevents the code from working properly.
> 
> `<node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz" args="-d $(find voxel_mapping)/rviz_cfg/voxel_mapping.rviz" />`
> 
> should be: `<node launch-prefix="nice" pkg="rviz" type="rviz" name="rviz" args="-d $(find voxel_map)/rviz_cfg/voxel_mapping.rviz" />`
> 
> Otherwise，there will be a error when running the launch file as follows:
> 
> Resource not found: voxel_mapping ROS path [0]=/opt/ros/noetic/share/ros ROS path [1]=/home/xxx/voxel_map_ws/src ROS path [2]=/opt/ros/noetic/share The traceback for the exception was written to the log file

Thank you for your report. I have updated the launch files.
