### ISSUE TITLE
How to build and maintain a consistent voxel map?

### ISSUE THREAD

**Issue by LiShuaixin** [hku-mars/VoxelMap#6]
Hi, @ChongjianYUAN, thanks for your sharing! I'm puzzled about the `buildVoxelMap()` and `updateVoxelMap()` in both of which you the local coordinate of  each laser point is used to determine the voxel key. From my understanding, the world coordinate instead of local coordinate should be used to find the key of each point, to maintain the consistency of the voxel map. Do you have any other consideration for this issue?

**Comment by ChongjianYUAN** [comment]
> Hi, @ChongjianYUAN, thanks for your sharing! I'm puzzled about the `buildVoxelMap()` and `updateVoxelMap()` in both of which you the local coordinate of each laser point is used to determine the voxel key. From my understanding, the world coordinate instead of local coordinate should be used to find the key of each point, to maintain the consistency of the voxel map. Do you have any other consideration for this issue?

Hi. You are right. The world coordinate should be used to find the key of each point and actu
ally, VoxelMap does use the world coordinate of each point to build and update the map. You can find it from the code.
![voxel_map_code](https://user-images.githubusercontent.com/51600805/178627798-7ac2585a-4fb0-4cb6-86b9-1148f0579a89.png)

**Comment by LiShuaixin** [comment]
Thanks for your quick reply! I just quickly skimmed through the code in `voxel_map_utils.hpp` and missed to check the code in `voxelMapping.cpp`. Sorry about that!
