### ISSUE TITLE
运行时，RVIZ显示卡顿

### ISSUE THREAD

**Issue by Sunnystaste** [hku-mars/VoxelMap#7]
您好！感谢您出色的工作！我有一个问题想请教您，目前我运行自己的avia采集的数据，数据都挺正常的，但是数据多了之后RVIZ显示就卡死了，请问如何缓解这个情况呢？
![image](https://user-images.githubusercontent.com/37181135/179642740-a6f79404-df8c-401e-94a9-6882dfdaf9dd.png)

**Comment by Sunnystaste** [comment]
![屏幕截图_1](https://user-images.githubusercontent.com/37181135/179650364-8c9b507a-99dd-4546-b6c3-a00345e95338.png)

**Comment by ChongjianYUAN** [comment]
尝试把publish_max_voxel_layer改成0试试，这样rviz只会显示少部分plane，也可以把publish_point_cloud设置为false

**Comment by Xu-Shilin** [comment]
在rviz里面关闭显示plane

**Comment by Sunnystaste** [comment]
我就是想显示平面但是不卡，电脑跑纯点云的开源框架都没事=-=，GTX1650TI，不至于呀

**Comment by jiejie567** [comment]
Leave a comment


> 我就是想显示平面但是不卡，电脑跑纯点云的开源框架都没事=-=，GTX1650TI，不至于呀

请问你解决了么？我的台式机3060显卡，publish_max_voxel_layer改成0也还是崩溃。

**Comment by KkCabin** [comment]
> Leave a comment
> 
> > 我就是想显示平面但是不卡，电脑跑纯点云的开源框架都没事=-=，GTX1650TI，不至于呀
> 
> 请问你解决了么？我的台式机3060显卡，publish_max_voxel_layer改成0也还是崩溃。


您好，请问这个问题你解决了吗？我也是在台式机上用3060ti，把publish_max_voxel_layer改成0还是崩溃。
